import {
  SiJavascript,
  SiTypescript,
  SiPython,
  SiReact,
  SiNextdotjs,
  SiNodedotjs,
  SiDocker,
  SiKubernetes,
  SiPostgresql,
  SiMysql,
  SiMongodb,
  SiRedis,
  SiAmazonwebservices,
  SiGooglecloud,
  SiGit,
  SiGithub,
  SiGraphql,
  SiTailwindcss,
  SiVuedotjs,
  SiAngular,
  SiRuby,
  SiPhp,
  SiGo,
  SiRust,
  SiSwift,
  SiKotlin,
  SiCplusplus,
  SiDotnet,
  SiElasticsearch,
  SiApachekafka,
  SiNginx,
  SiJenkins,
  SiTerraform,
  SiAnsible,
  SiFirebase,
  SiSupabase,
  SiPrisma,
  SiExpress,
  SiDjango,
  SiFlask,
  SiSpringboot,
  SiLaravel,
  SiRubyonrails,
  SiSvelte,
  SiSass,
  SiWebpack,
  SiVite,
} from "react-icons/si";
import { FaCode, FaJava, FaMicrosoft } from "react-icons/fa";
import { TbBrandCSharp } from "react-icons/tb";
import { IconType } from "react-icons";

export const techIconMap: Record<string, { icon: IconType; color: string }> = {
  javascript: { icon: SiJavascript, color: "#F7DF1E" },
  typescript: { icon: SiTypescript, color: "#3178C6" },
  python: { icon: SiPython, color: "#3776AB" },
  react: { icon: SiReact, color: "#61DAFB" },
  nextjs: { icon: SiNextdotjs, color: "#000000" },
  "next.js": { icon: SiNextdotjs, color: "#000000" },
  nodejs: { icon: SiNodedotjs, color: "#339933" },
  "node.js": { icon: SiNodedotjs, color: "#339933" },
  node: { icon: SiNodedotjs, color: "#339933" },
  docker: { icon: SiDocker, color: "#2496ED" },
  kubernetes: { icon: SiKubernetes, color: "#326CE5" },
  k8s: { icon: SiKubernetes, color: "#326CE5" },
  postgresql: { icon: SiPostgresql, color: "#4169E1" },
  postgres: { icon: SiPostgresql, color: "#4169E1" },
  mysql: { icon: SiMysql, color: "#4479A1" },
  mongodb: { icon: SiMongodb, color: "#47A248" },
  mongo: { icon: SiMongodb, color: "#47A248" },
  redis: { icon: SiRedis, color: "#DC382D" },
  aws: { icon: SiAmazonwebservices, color: "#FF9900" },
  "amazon web services": { icon: SiAmazonwebservices, color: "#FF9900" },
  gcp: { icon: SiGooglecloud, color: "#4285F4" },
  "google cloud": { icon: SiGooglecloud, color: "#4285F4" },
  azure: { icon: FaMicrosoft, color: "#0078D4" },
  git: { icon: SiGit, color: "#F05032" },
  github: { icon: SiGithub, color: "#181717" },
  graphql: { icon: SiGraphql, color: "#E10098" },
  tailwind: { icon: SiTailwindcss, color: "#06B6D4" },
  tailwindcss: { icon: SiTailwindcss, color: "#06B6D4" },
  vue: { icon: SiVuedotjs, color: "#4FC08D" },
  "vue.js": { icon: SiVuedotjs, color: "#4FC08D" },
  vuejs: { icon: SiVuedotjs, color: "#4FC08D" },
  angular: { icon: SiAngular, color: "#DD0031" },
  ruby: { icon: SiRuby, color: "#CC342D" },
  php: { icon: SiPhp, color: "#777BB4" },
  go: { icon: SiGo, color: "#00ADD8" },
  golang: { icon: SiGo, color: "#00ADD8" },
  rust: { icon: SiRust, color: "#000000" },
  swift: { icon: SiSwift, color: "#F05138" },
  kotlin: { icon: SiKotlin, color: "#7F52FF" },
  java: { icon: FaJava, color: "#007396" },
  "c++": { icon: SiCplusplus, color: "#00599C" },
  cpp: { icon: SiCplusplus, color: "#00599C" },
  "c#": { icon: TbBrandCSharp, color: "#239120" },
  csharp: { icon: TbBrandCSharp, color: "#239120" },
  ".net": { icon: SiDotnet, color: "#512BD4" },
  dotnet: { icon: SiDotnet, color: "#512BD4" },
  elasticsearch: { icon: SiElasticsearch, color: "#005571" },
  kafka: { icon: SiApachekafka, color: "#231F20" },
  nginx: { icon: SiNginx, color: "#009639" },
  jenkins: { icon: SiJenkins, color: "#D24939" },
  terraform: { icon: SiTerraform, color: "#7B42BC" },
  ansible: { icon: SiAnsible, color: "#EE0000" },
  firebase: { icon: SiFirebase, color: "#FFCA28" },
  supabase: { icon: SiSupabase, color: "#3FCF8E" },
  prisma: { icon: SiPrisma, color: "#2D3748" },
  express: { icon: SiExpress, color: "#000000" },
  "express.js": { icon: SiExpress, color: "#000000" },
  expressjs: { icon: SiExpress, color: "#000000" },
  django: { icon: SiDjango, color: "#092E20" },
  flask: { icon: SiFlask, color: "#000000" },
  spring: { icon: SiSpringboot, color: "#6DB33F" },
  "spring boot": { icon: SiSpringboot, color: "#6DB33F" },
  laravel: { icon: SiLaravel, color: "#FF2D20" },
  rails: { icon: SiRubyonrails, color: "#CC0000" },
  "ruby on rails": { icon: SiRubyonrails, color: "#CC0000" },
  svelte: { icon: SiSvelte, color: "#FF3E00" },
  sass: { icon: SiSass, color: "#CC6699" },
  scss: { icon: SiSass, color: "#CC6699" },
  webpack: { icon: SiWebpack, color: "#8DD6F9" },
  vite: { icon: SiVite, color: "#646CFF" },
};

export function getTechIcon(tech: string): { icon: IconType; color: string } {
  const normalizedTech = tech.toLowerCase().trim();

  return techIconMap[normalizedTech] || { icon: FaCode, color: "#6B7280" };
}
